name: publish package

on:
    push:
        branches:
            - master
        paths:
            - src/schema.json
            - .github/workflows/publish.yaml

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout sources
              uses: actions/checkout@v3

            # clientをcheckout ./distに
            - name: Checkout OpenAPI client repository
              uses: actions/checkout@v3
              with:
                  token: ${{ secrets.CLIENT_PAT }}
                  repository: sev3e3e/Splat3Api-Client
                  path: dist

            - name: Generate OpenAPI client
              uses: docker://openapitools/openapi-generator-cli
              with:
                  args: generate -i ./src/schema.json -g typescript-fetch -o ./dist/ --git-repo-id Splat3Api-Client --git-user-id sev3e3e --additional-properties=supportsES6=true,typescriptThreePlus=true,npmName=splat3api-api-client

            - name: change onwer to runner
              run: sudo chown -R runner:runner .

            - name: Create PR for client repository
              id: cpr
              uses: peter-evans/create-pull-request@v4
              with:
                  token: ${{ secrets.CLIENT_PAT }}
                  path: dist
                  commit-message: '[actions/create-pull-request] update client'
                  delete-branch: true

            - name: Merge PR
              run: gh pr merge ${{ steps.cpr.outputs.pull-request-url }} --squash --delete-branch
              env:
                  GH_TOKEN: ${{ secrets.CLIENT_PAT }}
